// <auto-generated />
using System;
using CareService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CareService.Migrations
{
    [DbContext(typeof(CareContext))]
    [Migration("20241126021556_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CareService.Model.PetCare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HappinessLevel")
                        .HasColumnType("int");

                    b.Property<int>("HungerLevel")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastFed")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastPlayed")
                        .HasColumnType("datetime2");

                    b.Property<int>("PetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PetCares");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HappinessLevel = 50,
                            HungerLevel = 50,
                            LastFed = new DateTime(2024, 11, 25, 18, 15, 54, 956, DateTimeKind.Local).AddTicks(4237),
                            LastPlayed = new DateTime(2024, 11, 25, 18, 15, 54, 961, DateTimeKind.Local).AddTicks(1892),
                            PetId = 1
                        },
                        new
                        {
                            Id = 2,
                            HappinessLevel = 50,
                            HungerLevel = 50,
                            LastFed = new DateTime(2024, 11, 25, 18, 15, 54, 961, DateTimeKind.Local).AddTicks(3989),
                            LastPlayed = new DateTime(2024, 11, 25, 18, 15, 54, 961, DateTimeKind.Local).AddTicks(4016),
                            PetId = 2
                        },
                        new
                        {
                            Id = 3,
                            HappinessLevel = 50,
                            HungerLevel = 50,
                            LastFed = new DateTime(2024, 11, 25, 18, 15, 54, 961, DateTimeKind.Local).AddTicks(4021),
                            LastPlayed = new DateTime(2024, 11, 25, 18, 15, 54, 961, DateTimeKind.Local).AddTicks(4023),
                            PetId = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
