// <auto-generated />
using AdoptionService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdoptionService.Migrations
{
    [DbContext(typeof(AdoptionContext))]
    [Migration("20241119031827_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AdoptionService.Model.Pet", b =>
                {
                    b.Property<int>("PetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PetId"));

                    b.Property<string>("AdoptedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<bool>("IsAdopted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonalityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PetId");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            PetId = 1,
                            AdoptedBy = "",
                            Age = 3,
                            IsAdopted = false,
                            Name = "Max",
                            PersonalityType = "Friendly",
                            Type = "Dog"
                        },
                        new
                        {
                            PetId = 2,
                            AdoptedBy = "",
                            Age = 2,
                            IsAdopted = false,
                            Name = "Garfield",
                            PersonalityType = "Playful",
                            Type = "Cat"
                        },
                        new
                        {
                            PetId = 3,
                            AdoptedBy = "",
                            Age = 4,
                            IsAdopted = false,
                            Name = "Whiteshoes",
                            PersonalityType = "Protective",
                            Type = "Dog"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
