// <auto-generated />
using System;
using HealthMonitoringService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HealthMonitoringService.Migrations
{
    [DbContext(typeof(HealthContext))]
    [Migration("20241126022936_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HealthMonitoringService.Model.HealthStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlertMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsHealthy")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastChecked")
                        .HasColumnType("datetime2");

                    b.Property<int>("PetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("HealthStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlertMessage = "Pet is healthy!",
                            IsHealthy = true,
                            LastChecked = new DateTime(2024, 11, 25, 18, 29, 35, 514, DateTimeKind.Local).AddTicks(3299),
                            PetId = 1
                        },
                        new
                        {
                            Id = 2,
                            AlertMessage = "Pet is healthy!",
                            IsHealthy = true,
                            LastChecked = new DateTime(2024, 11, 25, 18, 29, 35, 519, DateTimeKind.Local).AddTicks(2180),
                            PetId = 2
                        },
                        new
                        {
                            Id = 3,
                            AlertMessage = "Pet is healthy!",
                            IsHealthy = true,
                            LastChecked = new DateTime(2024, 11, 25, 18, 29, 35, 519, DateTimeKind.Local).AddTicks(2235),
                            PetId = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
